### PR TITLE
Fix analog opening hours also updated png

### PR DESCRIPTION
**Pull request by lucasfth**
We have started to close at 15:30 on normal days and 13:30 Fridays. So I just fixed it.

### CODE REVIEW

**Comment by lucasfth** [comment]
I also just talked to AnalogIO. At some point, there will probably be an API for when Analog is open. But right now it does not exist.

**Comment by lucasfth** [comment]
image

**Comment by PhilipFlyvholm** [comment]
Could the analog logo be a smaller resolution since it is 4000px x ~4000px

**Comment by lucasfth** [comment]
> Could the analog logo be a smaller resolution since it is 4000px x ~4000px

Ups did not realize that it was so big.
I have made it 350x398p now.

**Review by PhilipFlyvholm — APPROVED** [review]

**Pull request merged**
